<img src="https://www.dmproperties.com/cms/wp-content/uploads/2015/10/crecimiento-sector-inmobiliario-espanol-610x407.jpg" alt="spotify" width="300"/>

<h1 style="text-align: center;">Limpieza de datos inmoviliarios</h1>

## Librerias a usar

In [1]:
import pandas as pd
import matplotlib.pylab as plt

## Lectura del archivo CSV obtenido del webscrapping

In [2]:
file='C:\\Users\\ADMIN\\Desktop\\prueba1\\Urbania_Venta.csv'

In [3]:
df=pd.read_csv(file,header=0)

In [4]:
df.head(20)

,direccion,distrito,metraje,dormitorios,precio
0,Av Cipriano Dulanto 1351,"Pueblo Libre, Lima",38 a 104 m² tot.,1 a 3 dorm.,"S/ 261,780"
1,"Av. San Luis esquina Av. Angamos Este, esquina...","San Borja, Lima",37 a 115 m² tot.,1 a 2 dorm.,"S/ 297,000"
2,"Av Javier Prado Oeste 2291, Magdalena del Mar","Magdalena, Lima",41 a 126 m² tot.,1 a 3 dorm.,"S/ 385,000"
3,Esquina de Schell con Grimaldo del Solar,"Miraflores, Lima",64 a 131 m² tot.,2 a 3 dorm.,"S/ 652,702"
4,"Av. Los Faisanes 485, Chorrillos","Chorrillos, Lima",38 a 66 m² tot.,1 a 3 dorm.,"S/ 212,000"
5,Calle Las Palmeras 291. San Isidro,"Orrantia, San Isidro",40 a 81 m² tot.,1 a 3 dorm.,"S/ 354,859"
6,Avenida Cesar Vallejo 320,"S/n, Lince",21 a 119 m² tot.,1 a 3 dorm.,"S/ 219,600"
7,Avenida General Felipe Salaverry 571,"Jesús María, Lima",39 a 75 m² tot.,1 a 3 dorm.,"S/ 290,000"
8,"Calle Alcalá 468, Urb. Residencial La Castella...","La Castellana, Santiago de Surco",95 a 153 m² tot.,2 a 4 dorm.,"S/ 649,762 · USD 173,270"
9,AV LUIS ALDANA 255,"Santa Catalina, La Victoria",38 a 76 m² tot.,1 a 2 dorm.,"S/ 366,000"
10,Calle Carlos Arrieta 271,"Barranco, Lima",40 a 88 m² tot.,1 a 2 dorm.,"S/ 370,830 · USD 98,888"
11,Av. Benavides 541 esquina con Alcanfores 495,"Leuro, Miraflores",50 a 214 m² tot.,1 a 3 dorm.,"S/ 402,375 · USD 107,300"
12,Av. 28 de julio 1365 miraflores,"San Antonio, Miraflores",87 a 178 m² tot.,3 dorm.,"S/ 750,000 · USD 200,000"
13,Av. Mariscal La Mar 1055 Miraflores,"Miraflores, Lima",42 a 137 m² tot.,1 a 3 dorm.,"S/ 507,000 · USD 130,000"
14,Ca. Las Acacias 263,"Malecon Armendariz, Miraflores",68 a 196 m² tot.,1 a 3 dorm.,"S/ 701,250 · USD 187,000"
15,"Av Javier Prado Oeste 650, Magdalena del Mar","Magdalena, Lima",100 m² tot.,3 dorm.,"S/ 579,000 · USD 158,000"
16,Penthouse 4 Dormitorios con Baño Incorporado C...,"Higuereta, Santiago de Surco",218 m² tot.,4 dorm.,"S/ 1,160,000 · USD 310,000"
17,CRISTOBAL DE PERALTA SUR 505,"Valle Hermoso, Santiago de Surco",743 m² tot.,NaN,"S/ 5,200,000 · USD 1,400,000"
18,Ingreso POR LAS Dunas,"La Planicie, La Molina",585 m² tot.,4 dorm.,"S/ 4,560,000 · USD 1,200,000"
19,Calle Fernandez Concha,"Miraflores, Lima",317 m² tot.,5 dorm.,"S/ 2,756,250 · USD 735,000"

## Escaneo de informacion (Dimension y Tipo de datos)

In [5]:
df.shape

(7500, 5)

In [6]:
df.dtypes

direccion      object
distrito       object
metraje        object
dormitorios    object
precio         object
dtype: object

# inicio del codigo

In [43]:
df['precio'] = df['precio'].astype(str)

In [44]:
def extraer_precios(precio):
    precio_soles = None
    precio_dolares = None
    
    if 'S/' in precio:
        try:
            precio_soles = int(precio.split('S/')[1].split('·')[0].strip().replace(',', ''))
        except ValueError:
            pass
    if 'USD' in precio:
        try:
            precio_dolares = int(precio.split('USD')[1].strip().replace(',', ''))
        except ValueError:
            pass
    
    return pd.Series([precio_soles, precio_dolares])

In [45]:
# Aplicar la función al dataframe
df[['precio soles(S/)', 'precio dolares(USD)']] = df['precio'].apply(extraer_precios)

In [46]:
df.head(20)

,direccion,distrito,metraje,dormitorios,precio,precio soles(S/),precio dolares(USD)
0,Av Cipriano Dulanto 1351,"Pueblo Libre, Lima",38 a 104 m² tot.,1 a 3 dorm.,"S/ 261,780",261780.0,NaN
1,"Av. San Luis esquina Av. Angamos Este, esquina...","San Borja, Lima",37 a 115 m² tot.,1 a 2 dorm.,"S/ 297,000",297000.0,NaN
2,"Av Javier Prado Oeste 2291, Magdalena del Mar","Magdalena, Lima",41 a 126 m² tot.,1 a 3 dorm.,"S/ 385,000",385000.0,NaN
3,Esquina de Schell con Grimaldo del Solar,"Miraflores, Lima",64 a 131 m² tot.,2 a 3 dorm.,"S/ 652,702",652702.0,NaN
4,"Av. Los Faisanes 485, Chorrillos","Chorrillos, Lima",38 a 66 m² tot.,1 a 3 dorm.,"S/ 212,000",212000.0,NaN
5,Calle Las Palmeras 291. San Isidro,"Orrantia, San Isidro",40 a 81 m² tot.,1 a 3 dorm.,"S/ 354,859",354859.0,NaN
6,Avenida Cesar Vallejo 320,"S/n, Lince",21 a 119 m² tot.,1 a 3 dorm.,"S/ 219,600",219600.0,NaN
7,Avenida General Felipe Salaverry 571,"Jesús María, Lima",39 a 75 m² tot.,1 a 3 dorm.,"S/ 290,000",290000.0,NaN
8,"Calle Alcalá 468, Urb. Residencial La Castella...","La Castellana, Santiago de Surco",95 a 153 m² tot.,2 a 4 dorm.,"S/ 649,762 · USD 173,270",649762.0,173270.0
9,AV LUIS ALDANA 255,"Santa Catalina, La Victoria",38 a 76 m² tot.,1 a 2 dorm.,"S/ 366,000",366000.0,NaN
10,Calle Carlos Arrieta 271,"Barranco, Lima",40 a 88 m² tot.,1 a 2 dorm.,"S/ 370,830 · USD 98,888",370830.0,98888.0
11,Av. Benavides 541 esquina con Alcanfores 495,"Leuro, Miraflores",50 a 214 m² tot.,1 a 3 dorm.,"S/ 402,375 · USD 107,300",402375.0,107300.0
12,Av. 28 de julio 1365 miraflores,"San Antonio, Miraflores",87 a 178 m² tot.,3 dorm.,"S/ 750,000 · USD 200,000",750000.0,200000.0
13,Av. Mariscal La Mar 1055 Miraflores,"Miraflores, Lima",42 a 137 m² tot.,1 a 3 dorm.,"S/ 507,000 · USD 130,000",507000.0,130000.0
14,Ca. Las Acacias 263,"Malecon Armendariz, Miraflores",68 a 196 m² tot.,1 a 3 dorm.,"S/ 701,250 · USD 187,000",701250.0,187000.0
15,"Av Javier Prado Oeste 650, Magdalena del Mar","Magdalena, Lima",100 m² tot.,3 dorm.,"S/ 579,000 · USD 158,000",579000.0,158000.0
16,Penthouse 4 Dormitorios con Baño Incorporado C...,"Higuereta, Santiago de Surco",218 m² tot.,4 dorm.,"S/ 1,160,000 · USD 310,000",1160000.0,310000.0
17,CRISTOBAL DE PERALTA SUR 505,"Valle Hermoso, Santiago de Surco",743 m² tot.,NaN,"S/ 5,200,000 · USD 1,400,000",5200000.0,1400000.0
18,Ingreso POR LAS Dunas,"La Planicie, La Molina",585 m² tot.,4 dorm.,"S/ 4,560,000 · USD 1,200,000",4560000.0,1200000.0
19,Calle Fernandez Concha,"Miraflores, Lima",317 m² tot.,5 dorm.,"S/ 2,756,250 · USD 735,000",2756250.0,735000.0

In [47]:
# Tasa de cambio de soles a dólares
tasa_cambio = 3.70

# Convertir los valores en soles a dólares donde no hay valor en dólares y formatear los valores en dólares
df['precio dolares(USD)'] = df.apply(lambda row: '{:.2f}'.format(row['precio soles(S/)'] / tasa_cambio) if pd.isna(row['precio dolares(USD)']) else '{:.2f}'.format(row['precio dolares(USD)']), axis=1)

In [49]:
df = df.drop(columns=['precio'])

In [50]:
df.head(20)

,direccion,distrito,metraje,dormitorios,precio soles(S/),precio dolares(USD)
0,Av Cipriano Dulanto 1351,"Pueblo Libre, Lima",38 a 104 m² tot.,1 a 3 dorm.,261780.0,70751.35
1,"Av. San Luis esquina Av. Angamos Este, esquina...","San Borja, Lima",37 a 115 m² tot.,1 a 2 dorm.,297000.0,80270.27
2,"Av Javier Prado Oeste 2291, Magdalena del Mar","Magdalena, Lima",41 a 126 m² tot.,1 a 3 dorm.,385000.0,104054.05
3,Esquina de Schell con Grimaldo del Solar,"Miraflores, Lima",64 a 131 m² tot.,2 a 3 dorm.,652702.0,176405.95
4,"Av. Los Faisanes 485, Chorrillos","Chorrillos, Lima",38 a 66 m² tot.,1 a 3 dorm.,212000.0,57297.30
5,Calle Las Palmeras 291. San Isidro,"Orrantia, San Isidro",40 a 81 m² tot.,1 a 3 dorm.,354859.0,95907.84
6,Avenida Cesar Vallejo 320,"S/n, Lince",21 a 119 m² tot.,1 a 3 dorm.,219600.0,59351.35
7,Avenida General Felipe Salaverry 571,"Jesús María, Lima",39 a 75 m² tot.,1 a 3 dorm.,290000.0,78378.38
8,"Calle Alcalá 468, Urb. Residencial La Castella...","La Castellana, Santiago de Surco",95 a 153 m² tot.,2 a 4 dorm.,649762.0,173270.00
9,AV LUIS ALDANA 255,"Santa Catalina, La Victoria",38 a 76 m² tot.,1 a 2 dorm.,366000.0,98918.92
10,Calle Carlos Arrieta 271,"Barranco, Lima",40 a 88 m² tot.,1 a 2 dorm.,370830.0,98888.00
11,Av. Benavides 541 esquina con Alcanfores 495,"Leuro, Miraflores",50 a 214 m² tot.,1 a 3 dorm.,402375.0,107300.00
12,Av. 28 de julio 1365 miraflores,"San Antonio, Miraflores",87 a 178 m² tot.,3 dorm.,750000.0,200000.00
13,Av. Mariscal La Mar 1055 Miraflores,"Miraflores, Lima",42 a 137 m² tot.,1 a 3 dorm.,507000.0,130000.00
14,Ca. Las Acacias 263,"Malecon Armendariz, Miraflores",68 a 196 m² tot.,1 a 3 dorm.,701250.0,187000.00
15,"Av Javier Prado Oeste 650, Magdalena del Mar","Magdalena, Lima",100 m² tot.,3 dorm.,579000.0,158000.00
16,Penthouse 4 Dormitorios con Baño Incorporado C...,"Higuereta, Santiago de Surco",218 m² tot.,4 dorm.,1160000.0,310000.00
17,CRISTOBAL DE PERALTA SUR 505,"Valle Hermoso, Santiago de Surco",743 m² tot.,NaN,5200000.0,1400000.00
18,Ingreso POR LAS Dunas,"La Planicie, La Molina",585 m² tot.,4 dorm.,4560000.0,1200000.00
19,Calle Fernandez Concha,"Miraflores, Lima",317 m² tot.,5 dorm.,2756250.0,735000.00